[build]
  publish = "frontend"
  command = ""

[[redirects]]
  from = "/"
  to = "/index.backend.html"
  status = 200

[[redirects]]
  from = "/pro"
  to = "/pro.html"
  status = 200

[[redirects]]
  from = "/frontend/*"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.{jpg,jpeg,png,gif,svg,webp}"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"