services:
  - type: web
    name: wayzo-trip-planner
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./frontend
    routes:
      - type: rewrite
        source: /*
        destination: /index.backend.html
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        fromService:
          type: secret
          name: openai-api-key