<document filename="ics.mjs">
function uid() { return Math.random().toString(36).slice(2); }
function fmt(dt) {
  const d = new Date(dt);
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;
}
/** events: [{ title, date:'YYYY-MM-DD', start:'09:00', end:'11:00', location }] */
export function buildIcs(planId = 'wayzo', events = [], meta = {}) {
  const lines = [
    'BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Wayzo//Trip Plan//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',
    'X-WR-TIMEZONE:UTC',
  ];
  for (const ev of events) {
    const [sh='09:00', eh='11:00'] = [ev.start || '09:00', ev.end || '11:00'].map(t => t.split(':'));
    const s = new Date(`${ev.date}T${sh[0]}:${sh[1]}:00Z`);
    const e = new Date(`${ev.date}T${eh[0]}:${eh[1]}:00Z`);
    lines.push(
      'BEGIN:VEVENT',
      `UID:${uid()}@wayzo`,
      `DTSTAMP:${fmt(new Date())}`,
      `DTSTART:${fmt(s)}`,
      `DTEND:${fmt(e)}`,
      `SUMMARY:${(ev.title || 'Wayzo Event').replace(/\r?\n/g,' ')}`,
      ev.location ? `LOCATION:${ev.location.replace(/\r?\n/g,' ')}` : '',
      `DESCRIPTION:${(meta.destination ? meta.destination + ' — ' : '')}Generated by Wayzo`,
      'END:VEVENT'
    );
  }
  lines.push('END:VCALENDAR');
  return lines.join('\r\n');
}
</document>